browser:
  browserName: chrome
  headlessBrowser: false
  webElementTimeOut: 15

environment:
  test:
    envName: test
    appUrl: https://www.saucedemo.com/
    standard_username: standard_user
    problem_username: problem_user
    performance_username: performance_glitch_user
    incorrect_username: incorrect_username
    password: secret_sauce
    incorrect_password: incorrect_password
    bad_credentials_message:  "Epic sadface: Username and password do not match any user in this service"
    headerTitle: PRODUCTS


    email: mariankowalski@tes.com
    age: 65
    profession: 2
    continent: europe
    seleniumCommand1: navigation-commands
    seleniumCommand2: wait-commands
    expectedMsg: Form send with success
    path: src/main/resources/file.txt
    active: true
  test2:
    envName: test2
    appUrl: https://seleniumui.moderntester.pl/form.php
    firstName: Jan
    lastName: Nowak
    email: jannowak@tes.com
    age: 44
    profession: 1
    continent: asia
    seleniumCommand1: switch-commands
    seleniumCommand2: wait-commands
    expectedMsg: Form send with success
    path: src/main/resources/file.txt
    active: false
