browser:
  browserName: chrome
  headlessBrowser: false
  webElementTimeOut: 20

environment:
  test:
    envName: test
    appUrl: https://www.saucedemo.com/
    standard_username: standard_user
    problem_username: problem_user
    performance_username: performance_glitch_user
    incorrect_username: incorrect_username
    password: secret_sauce
    incorrect_password: incorrect_password
    bad_credentials_message: "Epic sadface: Username and password do not match any user in this service"
    headerTitle: PRODUCTS
    active: true
  test2:
    envName: test2
    appUrl: https://www.saucedemo.com/
    standard_username: standard_user
    problem_username: problem_user
    performance_username: performance_glitch_user
    incorrect_username: incorrect_username
    password: secret_sauce
    incorrect_password: incorrect_password
    bad_credentials_message: "Epic sadface: Username and password do not match any user in this service"
    headerTitle: PRODUCTS
    active: false
